import Link from "next/link";
import { notFound } from "next/navigation";
import { AdmissionForm } from "../../components/admission-form";
import { Arrow } from "../../components/icons";
import { GivingOptions } from "../../components/giving-options";
import { ExchangeForm } from "../../components/exchange-form";
import { peopleProfiles, type Profile } from "../../content/people";

type PageInfo = { label: string; title: string; emphasis: string; intro: string; image: string; eyebrow: string; details: string[]; facts: [string, string][]; cta?: string };

const pages: Record<string, PageInfo> = {
  academics: { label: "Academics", title: "Learning for Understanding, Application and Life", emphasis: "for every future.", eyebrow: "Curriculum", intro: "AMHS follows Uganda's national secondary education curriculum while promoting a learner-centred approach that emphasises understanding, application, creativity and problem-solving.", image: "curriculum", details: ["Academic learning is complemented by continuous assessment, Project-Based Learning, practical skills and co-curricular experiences.", "Our aim is not simply to prepare students for examinations. We want students to become independent thinkers, effective communicators, problem-solvers, innovators and responsible citizens."], facts: [["O-Level", "Core subjects"], ["S1–S6", "Full secondary"], ["A-Level", "Long-term plan"]], cta: "Explore subjects" },
  about: { label: "Who we are", title: "Education with Knowledge, Character and Purpose", emphasis: "for every learner.", eyebrow: "About AMHS", intro: "Asaba Memorial High School is a privately established mixed day and boarding secondary school serving Kiruli Sub-county, Masindi District and surrounding communities.", image: "about", details: ["The school was established in response to a clear local challenge: many children complete primary education but face difficulty continuing to secondary school because of distance, transport costs, boarding expenses and limited access to affordable nearby schools. AMHS therefore exists as a community-responsive institution committed to widening access to quality secondary education.", "Our approach brings together academic excellence, values and character, practical skills, leadership, inclusion, technology, creativity and community responsibility. The school is registered with the Uganda Registration Services Bureau under Certificate No. 80034317301770, and its Development Plan records its ongoing progression through the relevant education-sector licensing process."], facts: [["Mixed", "Day & boarding"], ["Registered", "URSB No. 80034317301770"], ["Values", "ASABA" ]], cta: "Meet our community" },
  "amhs-roots": { label: "Who we are", title: "A Legacy that Became a School", emphasis: "with purpose.", eyebrow: "AMHS Roots", intro: "Asaba Memorial High School was founded in honour of Abwooli Asaba Mary, a devoted mother who passed away on 21 March 2022.", image: "roots", details: ["Her life and legacy of compassion, resilience and commitment to uplifting others inspired the establishment of a school through which opportunities could be created for generations of young people. From that legacy emerged a bigger vision: to create a school capable of changing lives through accessible, transformative and values-based education.", "AMHS was established in Kitanyata because education remains one of the strongest pathways through which families and communities can build sustainable futures. The word Memorial represents more than remembrance: it represents continuing a legacy through service by serving underserved communities, expanding access, supporting vulnerable learners, developing responsible young leaders and turning education into practical community transformation."], facts: [["2022", "Foundation legacy"], ["Kitanyata", "School location"], ["Service", "Community mission"]], cta: "Read our story" },
  team: { label: "Who we are", title: "People Committed to Every Learner", emphasis: "and every future.", eyebrow: "Our Team", intro: "Behind every successful school is a community of people working together. AMHS brings together school leadership, teachers, administrative personnel, support staff, parents, governors and student leaders.", image: "team", details: ["Our teaching staff deliver classroom instruction while also supporting student guidance, supervision and co-curricular activities.", "Our administrative and support teams help manage records, finance, boarding, catering, sanitation, security, maintenance and student welfare."], facts: [["Leadership", "School leadership"], ["Support", "Parent & staff teams"], ["Student", "Voice & leadership"]], cta: "Meet our staff" },
  staff: { label: "Our team", title: "Our Staff", emphasis: "learning and care in action.", eyebrow: "Our Staff", intro: "Our teaching staff deliver classroom instruction while also supporting student guidance, supervision and co-curricular activities.", image: "team", details: ["Our administrative and support teams help manage records, finance, boarding, catering, sanitation, security, maintenance and student welfare.", "Together, they create an environment where learners can develop academically and personally."], facts: [["Teaching", "Classroom excellence"], ["Support", "Welfare & operations"], ["Care", "Student guidance"]], cta: "Contact the school" },
  "board-of-governors": { label: "Our team", title: "Governance for Quality and Accountability", emphasis: "for the school community.", eyebrow: "Board of Governors", intro: "The Board of Governors provides institutional governance and oversight, helping ensure that AMHS operates responsibly and remains focused on its educational mission.", image: "board", details: ["The Board supports strategic direction, accountability, school development, learner welfare, policy oversight and engagement with the wider school community.", "The Board works closely with school leadership to keep students at the centre of every decision."], facts: [["Governance", "Strategic oversight"], ["Welfare", "Learner wellbeing"], ["Accountability", "Responsible leadership"]], cta: "Our governance" },
  "pta-leadership": { label: "Our team", title: "Parents as Partners in Education", emphasis: "in every learner's journey.", eyebrow: "PTA Leadership", intro: "AMHS recognises that educating a child requires cooperation between the school and the home.", image: "parents", details: ["The Parents Teachers Association provides an important link between parents, teachers and school administration.", "It supports dialogue on student welfare, discipline, academic performance and school development while strengthening parental participation in education."], facts: [["Partnership", "Home & school"], ["Welfare", "Student support"], ["Participation", "School development"]], cta: "Join the PTA" },
  "student-leadership": { label: "Our team", title: "Learning to Lead by Leading", emphasis: "with responsibility.", eyebrow: "Student Leadership", intro: "Leadership development should begin while young people are still learning.", image: "students", details: ["Student leadership at AMHS provides learners with opportunities to develop responsibility, communication, teamwork, accountability and service.", "Student leaders help promote positive behaviour, represent student concerns and support activities within the school community."], facts: [["Responsibility", "Student voice"], ["Leadership", "Service & teamwork"], ["Growth", "Confidence & accountability"]], cta: "Student life" },
  "success-stories": { label: "Who we are", title: "Every Journey Matters", emphasis: "and every story counts.", eyebrow: "Success Stories", intro: "Success at AMHS is not measured only by examination results. It can be seen when a learner improves academically, develops confidence, discovers a talent, learns a practical skill or becomes an example to others.", image: "success", details: ["Success can also mean assuming responsibility, overcoming difficult circumstances, contributing to a project, finding a voice through music or sport, or returning to serve the community.", "AMHS is committed to recognising the many forms of growth, achievement and contribution made by students. Future stories will celebrate learners whose progress shows what knowledge, character and purpose can make possible."], facts: [["Growth", "Academic & personal"], ["Talent", "Development"], ["Purpose", "Leadership & service"]], cta: "Share your story" },
  "school-policies": { label: "Who we are", title: "Creating a Safe and Responsible Learning Environment", emphasis: "for every learner.", eyebrow: "School Policies", intro: "Our policies establish clear standards for learning, conduct, accountability and student protection.", image: "policies", details: ["At AMHS, every learner has a right to a learning environment free from abuse, neglect, exploitation, violence and discrimination. Safeguarding covers prevention, reporting, safe recruitment, supervision, guidance and counselling.", "The downloadable policy centre can include the Child Protection & Safeguarding Policy, Students’ Code of Conduct, Staff Code of Conduct, Admissions Policy, Boarding Policy, Anti-Bullying Policy, ICT/Internet Policy, Health & Safety Policy, Academic Policy and Complaints Procedure."], facts: [["Safeguarding", "Child protection"], ["Support", "Guidance & counselling"], ["Standards", "Conduct & accountability"]], cta: "Request a policy" },
  partners: { label: "Who we are", title: "Working Together for Education", emphasis: "with real purpose.", eyebrow: "Our Partners", intro: "Meaningful educational transformation requires collaboration.", image: "partners", details: ["AMHS welcomes responsible partnerships with parents, communities, education authorities, development organisations, businesses, institutions, professionals and well-wishers who share our commitment to improving opportunities for young people.", "Partnership opportunities include student sponsorship, learning materials, ICT, vocational equipment, infrastructure, sports, school exchanges, teacher development, career guidance and technical support."], facts: [["Partnership", "Shared mission"], ["Support", "Student opportunities"], ["Growth", "Infrastructure & skills"]], cta: "Partner with us" },
  facilities: { label: "Who we are", title: "A Campus Built for Learning and Growth", emphasis: "with purpose.", eyebrow: "School Facilities", intro: "Our campus is being developed progressively to provide safe, functional spaces for academic learning, boarding, practical education and co-curricular development.", image: "facilities", details: ["Facilities include classrooms and an administration block; boarding facilities; a vocational skills block; a developing library; ICT and computer facilities; kitchen and feeding facilities; water infrastructure with an electric pump and distributed tap points; electricity connected to operational buildings; sanitation facilities; and playground and sports areas.", "The school’s longer-term development programme includes science laboratories, additional classrooms, dormitories, sports facilities and other learning infrastructure to meet the needs of a growing student population."], facts: [["Classrooms", "Teaching spaces"], ["Boarding", "Accommodation"], ["Practical", "Skills & learning"]], cta: "Plan a visit" },
  curriculum: { label: "Academics", title: "Learning for Understanding, Application and Life", emphasis: "at AMHS.", eyebrow: "Curriculum", intro: "AMHS follows Uganda's national secondary education curriculum while promoting a learner-centred approach that emphasises understanding, application, creativity and problem-solving.", image: "curriculum", details: ["Academic learning is complemented by continuous assessment, Project-Based Learning, practical skills and co-curricular experiences.", "Our aim is not simply to prepare students for examinations. We want students to become independent thinkers, effective communicators, problem-solvers, innovators and responsible citizens."], facts: [["O-Level", "Core subjects"], ["S1–S6", "Full secondary"], ["A-Level", "Long-term plan"]], cta: "Explore subjects" },
  "academic-calendar": { label: "Academics", title: "Plan the school year", emphasis: "with confidence.", eyebrow: "Academic Calendar", intro: "The AMHS calendar will organise opening, visiting days, assessment periods, candidate activities, examinations and closing dates for each term.", image: "calendar", details: ["Term I: Opening, Visiting Day, Assessment Period and Closing. Term II: Opening, Visiting Day, Assessment Period and Closing. Term III: Opening, Candidate Activities, Examinations and Closing.", "Because specific term dates are not contained in the Development Plan, the current approved annual calendar should be populated here when available. Families will receive important reminders through the school office."], facts: [["Term I", "Opening to closing"], ["Term II", "Opening to closing"], ["Term III", "Candidates & exams"]], cta: "Download calendar" },
  subjects: { label: "Academics", title: "Find the subjects", emphasis: "that spark you.", eyebrow: "Subjects Offered", intro: "Students can pursue a strong core of academic subjects and explore the areas that engage their interests and ambitions.", image: "subjects", details: ["The O-Level programme includes Geography, Biology, Physics, Mathematics, Chemistry, History & Political Education, English Language, Agriculture, Fine Art, ICT, Christian Religious Education, Kiswahili, Literature in English, Entrepreneurship Education and Physical Education.", "AMHS’s long-term A-Level development plan includes Physics, Chemistry, Biology, Mathematics, Agriculture, ICT, History, Geography, Economics, Divinity, Literature in English, Kiswahili and Entrepreneurship. Learning extends beyond exam preparation to help students understand the world and their place within it."], facts: [["15", "O-Level subjects"], ["STEM", "Sciences & maths"], ["A-Level", "Long-term plan"]], cta: "Talk to academics" },
  library: { label: "Academics", title: "Building a culture of", emphasis: "reading and discovery.", eyebrow: "School Library", intro: "The AMHS library is intended to become more than a room containing books. It will serve as a centre for reading, research, independent study and intellectual discovery.", image: "library", details: ["Students are encouraged to use library resources to deepen classroom learning, explore personal interests and develop lifelong reading habits.", "As the library develops, it will support quiet study, guided research, reading lists and the independent learning habits that carry students beyond school."], facts: [["Reading", "Lifelong habits"], ["Research", "Independent study"], ["Discovery", "Personal interests"]], cta: "Visit the library" },
  syllabus: { label: "Academics", title: "A clear route", emphasis: "to achievement.", eyebrow: "National & School Syllabus", intro: "AMHS aligns academic delivery with the applicable national curriculum and syllabus requirements.", image: "syllabus", details: ["The National Syllabus section can organise approved resources by O-Level, subject and class or level. School academic resources can include schemes of work, revision guides, holiday work, reading lists, assessment guides and project guidelines.", "These resources will provide students, parents and teachers with an organised route to learning, revision, assessment and project work."], facts: [["Aligned", "National syllabus"], ["Mapped", "Progression"], ["Shared", "With families"]], cta: "Get syllabus information" },
  admission: { label: "Admission", title: "Begin Your AMHS", emphasis: "Journey.", eyebrow: "Join AMHS", intro: "Choosing a secondary school is an important decision for every learner and family. AMHS welcomes students who are ready to learn, develop their abilities and participate positively in school life.", image: "admission", details: ["We provide both day and boarding options, enabling families to select the arrangement most appropriate for their circumstances. The online application is designed to be simple enough for a parent using a mobile phone.", "The admissions team will guide families through student details, parent or guardian information, admission type, educational information, additional needs, required documents and the declaration before reviewing the application and contacting the family about the next stage."], facts: [["Day", "Day scholar option"], ["Boarding", "Boarding student option"], ["Support", "Admissions guidance"]], cta: "Apply now" },
  fees: { label: "Admission", title: "Simple, clear", emphasis: "planning.", eyebrow: "Fees Structure", intro: "We present our fees clearly so families can plan with confidence. Please contact the school or download the current official fees structure before making payment.", image: "fees", details: ["The Development Plan currently records indicative term fees of UGX 150,000 for a day student and UGX 300,000 for a boarding student.", "The official fees sheet can separately show tuition, boarding, meals, uniform, development requirements and other approved charges. Fees and requirements may be reviewed, so families should confirm the current position with the school before payment."], facts: [["UGX 150,000", "Indicative day fee"], ["UGX 300,000", "Indicative boarding fee"], ["Confirm", "Current official fees"]], cta: "Ask about fees" },
  uniform: { label: "Admission", title: "Proud to belong.", emphasis: "Ready to learn.", eyebrow: "School Uniform", intro: "The AMHS uniform represents belonging, discipline, equality and pride in our school community.", image: "uniform", details: ["All students are expected to maintain the approved uniform neatly and responsibly. The requirements will cover day uniform, boarding requirements, sportswear, sweater, shoes, socks and school bag requirements.", "The school will provide actual photographs of male and female students wearing the approved uniform, together with a downloadable uniform and personal-requirements checklist."], facts: [["Everyday", "Day uniform"], ["Boarding", "Personal requirements"], ["Active", "Sportswear"]], cta: "Request a uniform list" },
  "our-approach": { label: "Our approach", title: "Purposeful learning.", emphasis: "Real-world courage.", eyebrow: "How we learn", intro: "We help students learn by doing, reflecting, connecting and contributing—because the richest learning changes both the mind and the person.", image: "approach", details: ["Project-based learning gives students a reason to ask good questions, solve real problems and share their work with a genuine audience.", "From school exchanges and brass band to sport, talent development and clubs, every experience grows confidence and connection."], facts: [["PBL", "Hands-on learning"], ["BBC", "Brass Band Club"], ["24", "Clubs & activities"]], cta: "Explore student life" },
  "project-based-learning": { label: "Our approach", title: "Learn. Create. Solve.", emphasis: "Apply with purpose.", eyebrow: "Project-Based Learning", intro: "Project-Based Learning is a central element of the AMHS approach. Students explore real problems, develop ideas, create solutions and present what they have learned.", image: "approach", details: ["Projects connect learning with agriculture, ICT, entrepreneurship, tailoring, carpentry, soap making, the environment and community challenges.", "A project might connect Mathematics with budgeting, Agriculture with crop production, ICT with digital communication or Entrepreneurship with developing and costing a simple product. Students strengthen research, communication, creativity, teamwork and practical application."], facts: [["PBL", "Learning by doing"], ["8", "Practical themes"], ["Real-world", "Meaningful projects"]], cta: "Explore our approach" },
  "brass-band-club": { label: "Our approach", title: "Music. Discipline.", emphasis: "Teamwork. Confidence.", eyebrow: "Brass Band Club", intro: "The AMHS Brass Band Club provides students with an opportunity to discover and develop musical talent while learning teamwork, discipline, concentration and performance skills.", image: "life", details: ["Students progressively learn musical instruments, music reading, marching, ensemble performance and public presentation.", "The Club looks forward to participating in school ceremonies, community events, national celebrations, competitions, exchange programmes and special performances."], facts: [["BBC", "Brass Band Club"], ["Music", "Shared expression"], ["Teamwork", "Playing as one"]], cta: "Discover student life" },
  "games-and-sport": { label: "Our approach", title: "Strong Bodies. Strong Minds.", emphasis: "Strong Teams.", eyebrow: "Games & Sports", intro: "Sports form an important part of holistic education at AMHS.", image: "life", details: ["Through games and physical activities, learners develop fitness, discipline, resilience, teamwork, leadership and healthy competition.", "The school’s developing playground is intended to support sports and co-curricular activities. Competition matters, but character matters more: respect, resilience and a generous team spirit guide every game."], facts: [["Active", "Fitness & wellbeing"], ["Growth", "Discipline & resilience"], ["Teamwork", "On and off the field"]], cta: "Explore student life" },
  "talent-development": { label: "Our approach", title: "Every learner has", emphasis: "potential.", eyebrow: "Talent Development", intro: "Not every child’s greatest ability appears on an examination paper. AMHS seeks to identify and develop talent in music, sports, art, public speaking, leadership, technology, entrepreneurship, craftsmanship and creative performance.", image: "life", details: ["Talent development follows three stages: Discover, Develop and Demonstrate. Students discover abilities, receive guidance and practise, then demonstrate those abilities through exhibitions, performances, competitions, projects and community activities.", "Supportive mentors help each learner set ambitious goals and celebrate the progress that comes from steady effort."], facts: [["Discover", "Find a strength"], ["Develop", "Practise with guidance"], ["Demonstrate", "Share and contribute"]], cta: "Discover student life" },
  "associations-and-clubs": { label: "Our approach", title: "Find your people.", emphasis: "Make your mark.", eyebrow: "Associations & Clubs", intro: "Clubs create spaces where learners can explore interests, practise leadership and develop friendships beyond normal classroom lessons.", image: "life", details: ["The programme can include Debate & Public Speaking, ICT & Innovation, Scripture or Christian Fellowship, Music & Performing Arts, and Writers & Readers.", "Students can join established clubs or help shape new ones around the ideas and causes that matter to them. These communities build confidence, responsibility and the joy of doing something worthwhile together."], facts: [["Explore", "Interests & ideas"], ["Lead", "Student responsibility"], ["Belong", "Friendship & community"]], cta: "Explore student life" },
  "students-life": { label: "Student life", title: "More Than", emphasis: "a School Day.", eyebrow: "Life at AMHS", intro: "Life at AMHS is designed around learning, friendship, responsibility, creativity and personal growth.", image: "life", details: ["Students experience a structured environment combining classroom learning with practical education, sports, clubs, leadership, guidance and social development. Boarding learners also develop independence, responsibility, cooperation and respect.", "Guidance and counselling support learners through adolescence. Safeguarding covers prevention, reporting, professional boundaries, supervision, safe recruitment, counselling and appropriate referral. A typical experience moves from morning preparation to classes, break, academic lessons, lunch, practical or project learning, sports or clubs and evening preparation for boarders."], facts: [["Together", "Learning & friendship"], ["Guidance", "Welfare & mentoring"], ["Belong", "Clubs, sports & leadership"]], cta: "See our approach" },
  "get-involved": { label: "Get involved", title: "Help Us Light", emphasis: "Another Path.", eyebrow: "Support AMHS", intro: "A child’s future should not be determined solely by where that child was born or the financial circumstances of the family.", image: "involved", details: ["Support can strengthen books and learning materials, ICT equipment, science facilities, library development, vocational equipment, sports equipment, boarding facilities, classroom development, water and sanitation, and student support.", "Through donations, sponsorships and partnerships, individuals and organisations can help expand educational opportunities. Payment information will only be published after the school’s official receiving account or mobile-money arrangements have been formally approved."], facts: [["Give", "Create opportunity"], ["Sponsor", "Support a learner"], ["Partner", "Strengthen AMHS"]], cta: "Make a difference" },
  "news-and-events": { label: "News and Events", title: "A school community in motion", emphasis: "with learning, celebration and service.", eyebrow: "News and Events", intro: "AMHS is building a campus culture that celebrates learning, milestones, school life and community engagement.", image: "curriculum", details: ["News and events at AMHS will highlight student achievement, school activities, outreach, open days, community partnerships and meaningful moments across the academic year.", "We welcome families, partners and friends to follow the life of the school and celebrate the progress of our learners."], facts: [["School life", "Student achievement"], ["Community", "Events & outreach"], ["Growth", "Shared milestones"]], cta: "Stay connected" },
  "contact-us": { label: "Contact Us", title: "We are here to help", emphasis: "and to welcome you.", eyebrow: "Contact AMHS", intro: "We are happy to help with admissions enquiries, general school questions, partnerships and support opportunities.", image: "involved", details: ["Whether you want to find out more about the school, request a visit, discuss sponsorship or ask about admissions, the AMHS team is ready to assist.", "Please use the details below to get in touch and we will help you with the next step."], facts: [["Admissions", "School enquiries"], ["Partnerships", "School exchanges"], ["Support", "Sponsorship & giving"]], cta: "Get in touch" },
  "school-exchange-programmes": { label: "Get involved", title: "Connecting Classrooms", emphasis: "and cultures.", eyebrow: "School Exchange Programmes", intro: "AMHS seeks to broaden students’ understanding of the world beyond their immediate community through meaningful exchange relationships.", image: "exchange", details: ["Potential activities include student-to-student correspondence, virtual classroom exchanges, joint projects, cultural exchange, teacher collaboration, educational visits, sports exchanges and arts exchanges.", "AMHS welcomes schools and educational institutions interested in mutual learning rather than one-way assistance. Conversations can begin with the school or organisation name, country, contact person, email, proposed exchange type and a message."], facts: [["Connect", "Classrooms & cultures"], ["Create", "Joint projects"], ["Share", "Mutual learning"]], cta: "Start a conversation" },
};

type PageFamily = "story" | "people" | "learning" | "practical" | "experience" | "community";

const pageHeadings: Record<string, [string, string]> = {
  academics: ["Ambition with", "the right support."], about: ["The values behind", "our school."], "amhs-roots": ["A story worth", "carrying forward."],
  team: ["Teaching, mentoring,", "and belonging."], staff: ["Dedicated to each", "student’s growth."], "board-of-governors": ["Leadership with students", "at the centre."],
  "pta-leadership": ["Home and school", "working together."], "student-leadership": ["A voice, a responsibility,", "a chance to lead."], "success-stories": ["What our community", "carries forward."],
  "school-policies": ["The guidance that keeps", "our community safe."], partners: ["Partnerships with", "real purpose."], facilities: ["A campus ready for", "every kind of learning."],
  curriculum: ["A clear journey through", "knowledge and possibility."], "academic-calendar": ["Plan the year", "with confidence."], subjects: ["Areas of study that", "open up choices."],
  library: ["Time and space", "to think deeply."], syllabus: ["What students learn,", "and how it builds."], admission: ["Everything families need", "to begin well."],
  fees: ["Straightforward support", "for family planning."], uniform: ["What students need", "to feel ready."], "our-approach": ["How learning becomes", "part of who students are."],
  "project-based-learning": ["Questions, action,", "and meaningful work."], "brass-band-club": ["Practice, performance,", "and pride."], "games-and-sport": ["A place to play,", "compete, and grow."],
  "talent-development": ["A pathway for", "every strength."], "associations-and-clubs": ["Interests become", "a sense of belonging."], "students-life": ["A school day with", "more to discover."],
  "get-involved": ["Ways to make", "a lasting difference."], "news-and-events": ["What is happening", "across the school."], "contact-us": ["A warm welcome", "from the AMHS team."], "school-exchange-programmes": ["New perspectives", "that travel both ways."],
};

const actionDestinations: Record<string, string> = {
  academics: "/subjects", about: "/team", "amhs-roots": "/about", team: "/staff", staff: "mailto:info@amhs.sc.ug",
  "board-of-governors": "mailto:info@amhs.sc.ug", "pta-leadership": "mailto:info@amhs.sc.ug", "student-leadership": "/students-life",
  "success-stories": "mailto:info@amhs.sc.ug", "school-policies": "mailto:info@amhs.sc.ug", partners: "mailto:info@amhs.sc.ug", facilities: "/apply-now",
  curriculum: "/subjects", "academic-calendar": "mailto:info@amhs.sc.ug", subjects: "mailto:info@amhs.sc.ug", library: "mailto:info@amhs.sc.ug",
  syllabus: "mailto:info@amhs.sc.ug", admission: "/apply-now", fees: "mailto:info@amhs.sc.ug", uniform: "mailto:info@amhs.sc.ug",
  "our-approach": "/students-life", "project-based-learning": "/our-approach", "brass-band-club": "/students-life", "games-and-sport": "/students-life",
  "talent-development": "/students-life", "associations-and-clubs": "/students-life", "students-life": "/our-approach", "get-involved": "/donate",
  "news-and-events": "/news-and-events", "contact-us": "mailto:info@amhs.sc.ug",
  "school-exchange-programmes": "mailto:info@amhs.sc.ug",
};

const familyContent: Record<PageFamily, { label: string; title: string; emphasis: string; description: string }> = {
  story: { label: "The bigger picture", title: "A shared", emphasis: "sense of purpose.", description: "The details below show the people, values and experiences that shape this part of AMHS." },
  people: { label: "People first", title: "The relationships", emphasis: "behind the work.", description: "Every role contributes to a school where young people are known, challenged and supported." },
  learning: { label: "Learning in practice", title: "Strong foundations.", emphasis: "Wider horizons.", description: "This is how students build knowledge, confidence and the habits that carry learning forward." },
  practical: { label: "Useful information", title: "The details", emphasis: "families need.", description: "Clear information helps students and families plan confidently for the next step." },
  experience: { label: "Beyond the classroom", title: "A chance to", emphasis: "take part and grow.", description: "These experiences give students room to practise, contribute and find what matters to them." },
  community: { label: "Together with AMHS", title: "Shared effort.", emphasis: "Real opportunity.", description: "This work connects the school with families, partners and a wider community of support." },
};

const mediaClass = (key: string) => `page-photo image-${key}`;

function getPageFamily(slug: string): PageFamily {
  if (["academics", "curriculum", "library"].includes(slug)) return "learning";
  if (["academic-calendar", "subjects", "syllabus", "fees", "uniform", "school-policies", "facilities", "admission"].includes(slug)) return "practical";
  if (["team", "staff", "board-of-governors", "pta-leadership", "student-leadership"].includes(slug)) return "people";
  if (["our-approach", "project-based-learning", "brass-band-club", "games-and-sport", "talent-development", "associations-and-clubs", "students-life"].includes(slug)) return "experience";
  if (["partners", "get-involved", "news-and-events", "contact-us", "school-exchange-programmes"].includes(slug)) return "community";
  return "story";
}

function PageAction({ slug, label }: { slug: string; label: string }) {
  const href = actionDestinations[slug] ?? "/apply-now";
  const content = <>{label} <Arrow /></>;
  return href.startsWith("mailto:")
    ? <a className="button button-navy" href={href}>{content}</a>
    : <Link className="button button-navy" href={href}>{content}</Link>;
}

function TopicOverview({ page, family }: { page: PageInfo; family: PageFamily }) {
  const content = familyContent[family];
  return <section className={`topic-section topic-section--${family}`}>
    <div className="container">
      <div className="topic-heading">
        <div><p className="eyebrow"><span /> {content.label}</p><h2>{content.title}<br /><em>{content.emphasis}</em></h2></div>
        <p>{content.description}</p>
      </div>
      <div className="topic-grid">
        {page.facts.map(([value, label], index) => <article className="topic-card" key={`${value}-${label}`}>
          <span className="topic-number">0{index + 1}</span><strong>{value}</strong><h3>{label}</h3>
          <p>{page.details[index] ?? `Find out more about ${label.toLowerCase()} and what it means for the AMHS community.`}</p>
        </article>)}
      </div>
    </div>
  </section>;
}

function ProfileDirectory({ type }: { type: "team" | "staff" }) {
  const isLeadership = type === "team";
  const profiles = peopleProfiles[type];
  return <section className="profiles-section">
    <div className="container">
      <div className="profiles-heading">
        <div><p className="eyebrow"><span /> {isLeadership ? "Meet the leadership team" : "Meet our staff"}</p><h2>{isLeadership ? "Guided by care." : "Expertise in every"}<br /><em>{isLeadership ? "Focused on every learner." : "part of school life."}</em></h2></div>
        <p>{isLeadership ? "Our leadership team creates the conditions for excellent learning, strong relationships and a school community that stays true to its values." : "Our teaching and support teams bring specialist knowledge, personal care and a shared commitment to helping young people flourish."}</p>
      </div>
      <div className="profile-grid">
        {profiles.map((profile) => <article className="profile-card" key={profile.name}>
          <div className={`profile-avatar${profile.image ? " has-photo" : ""}`} aria-hidden="true" style={profile.image ? { backgroundImage: `url(${profile.image})` } : undefined}>{profile.image ? "" : profile.initials}</div>
          <p>{profile.role}</p><h3>{profile.name}</h3><span className="profile-rule" />
          <p className="profile-bio">{profile.bio}</p>
        </article>)}
      </div>
      <p className="profiles-contact">For a school enquiry or to reach the right member of the team, <a href="mailto:info@amhs.sc.ug">contact the school office</a>.</p>
    </div>
  </section>;
}

export function generateStaticParams() {
  return [...Object.keys(pages), "apply-now", "donate", "sponsor-a-child"].map((slug) => ({ slug }));
}

export default async function ContentPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  if (slug === "apply-now") return <ApplyPage />;
  if (slug === "donate" || slug === "sponsor-a-child") return <GivingPage sponsor={slug === "sponsor-a-child"} />;
  const page = pages[slug];
  if (!page) notFound();
  const [sectionTitle, sectionEmphasis] = pageHeadings[slug] ?? [page.eyebrow, "at AMHS."];
  const family = getPageFamily(slug);

  return <>
    <section className="page-hero"><div className={mediaClass(page.image)} /><div className="page-hero-overlay" /><div className="container page-hero-content"><p className="eyebrow eyebrow-light"><span /> {page.label}</p><h1>{page.title}<br /><em>{page.emphasis}</em></h1><p>{page.intro}</p></div></section>
    <section className={`content-section content-section--${family} container`}><div className="content-copy"><p className="eyebrow"><span /> {page.eyebrow}</p><h2>{sectionTitle}<br /><em>{sectionEmphasis}</em></h2>{page.details.map((detail) => <p key={detail}>{detail}</p>)}<PageAction slug={slug} label={page.cta ?? "Get in touch"} /></div><aside className="facts-card"><p>At a glance</p>{page.facts.map(([value, label]) => <div key={`${value}-${label}`}><strong>{value}</strong><span>{label}</span></div>)}</aside></section>
    {slug === "team" || slug === "staff" ? <ProfileDirectory type={slug} /> : <TopicOverview page={page} family={family} />}
    {slug === "school-exchange-programmes" ? <section className="application-section container"><ExchangeForm /></section> : null}
  </>;
}

function ApplyPage() { return <><section className="page-hero page-hero-short"><div className="page-photo image-admission" /><div className="page-hero-overlay" /><div className="container page-hero-content"><p className="eyebrow eyebrow-light"><span /> Admission</p><h1>Let&apos;s begin<br /><em>together.</em></h1><p>Your child&apos;s AMHS story can start with a simple conversation.</p></div></section><section className="application-section container"><div className="application-aside"><p className="eyebrow"><span /> A personal process</p><h2>Every application starts with <em>getting to know you.</em></h2><p>We take time to understand each applicant and help your family decide whether AMHS is the right fit.</p><ol><li><span>01</span> Send your enquiry</li><li><span>02</span> Speak with admissions</li><li><span>03</span> Visit, apply, and belong</li></ol><a href="mailto:admissions@amhs.ac.ug" className="text-link">Have a question? Email us <Arrow /></a></div><AdmissionForm /></section></> }

function GivingPage({ sponsor }: { sponsor: boolean }) { const heading = sponsor ? ["A chance to learn.", "A future to build."] : ["Give a little.", "Change a lot."]; return <><section className="page-hero page-hero-short"><div className="page-photo image-involved" /><div className="page-hero-overlay" /><div className="container page-hero-content"><p className="eyebrow eyebrow-light"><span /> {sponsor ? "Sponsor a child" : "Donate"}</p><h1>{heading[0]}<br /><em>{heading[1]}</em></h1><p>{sponsor ? "Your monthly support can keep a child learning, growing and dreaming." : "Your gift goes directly toward opening up opportunity for our students."}</p></div></section><section className="giving-section container"><div className="giving-copy"><p className="eyebrow"><span /> Make an impact</p><h2>Small acts create <em>lasting possibility.</em></h2><p>When our wider community steps in, students can access the resources, experiences and encouragement they need to go further.</p><div className="impact-list"><span><b>01</b> Learning resources</span><span><b>02</b> Participation in activities</span><span><b>03</b> Student wellbeing</span></div></div><GivingOptions sponsor={sponsor} /></section></> }
