import Link from "next/link";
import { notFound } from "next/navigation";
import { AdmissionForm } from "../../components/admission-form";
import { Arrow } from "../../components/icons";
import { GivingOptions } from "../../components/giving-options";
import { peopleProfiles, type Profile } from "../../content/people";

type PageInfo = { label: string; title: string; emphasis: string; intro: string; image: string; eyebrow: string; details: string[]; facts: [string, string][]; cta?: string };

const pages: Record<string, PageInfo> = {
  academics: { label: "Academics", title: "Learning for Understanding, Application and Life", emphasis: "for every future.", eyebrow: "Curriculum", intro: "AMHS follows Uganda's national secondary education curriculum while promoting a learner-centred approach that emphasises understanding, application, creativity and problem-solving.", image: "curriculum", details: ["Academic learning is complemented by continuous assessment, Project-Based Learning, practical skills and co-curricular experiences.", "Our aim is not simply to prepare students for examinations. We want students to become independent thinkers, effective communicators, problem-solvers, innovators and responsible citizens."], facts: [["O-Level", "Core subjects"], ["S1–S6", "Full secondary"], ["A-Level", "Long-term plan"]], cta: "Explore subjects" },
  about: { label: "Who we are", title: "Education with Knowledge, Character and Purpose", emphasis: "for every learner.", eyebrow: "About AMHS", intro: "Asaba Memorial High School is a privately established mixed day and boarding secondary school serving Kiruli Sub-county, Masindi District and surrounding communities.", image: "about", details: ["The school was established in response to a clear local challenge: many children complete primary education but face difficulty continuing to secondary school because of distance, transport costs, boarding expenses and limited access to affordable nearby schools.", "AMHS therefore exists not merely as another school, but as a community-responsive educational institution committed to widening access to quality secondary education."], facts: [["Mixed", "Day & boarding"], ["Registered", "URSB No. 80034317301770"], ["Values", "ASABA" ]], cta: "Meet our community" },
  "amhs-roots": { label: "Who we are", title: "A Legacy that Became a School", emphasis: "with purpose.", eyebrow: "AMHS Roots", intro: "Asaba Memorial High School was founded in honour of Abwooli Asaba Mary, a devoted mother who passed away on 21 March 2022.", image: "roots", details: ["Her life and legacy of compassion, resilience and commitment to uplifting others inspired the establishment of a school through which opportunities could be created for generations of young people.", "From that legacy emerged a bigger vision: to create a school capable of changing lives through accessible, transformative and values-based education."], facts: [["2022", "Foundation legacy"], ["Kitanyata", "School location"], ["Service", "Community mission"]], cta: "Read our story" },
  team: { label: "Who we are", title: "People Committed to Every Learner", emphasis: "and every future.", eyebrow: "Our Team", intro: "Behind every successful school is a community of people working together. AMHS brings together school leadership, teachers, administrative personnel, support staff, parents, governors and student leaders.", image: "team", details: ["Our teaching staff deliver classroom instruction while also supporting student guidance, supervision and co-curricular activities.", "Our administrative and support teams help manage records, finance, boarding, catering, sanitation, security, maintenance and student welfare."], facts: [["Leadership", "School leadership"], ["Support", "Parent & staff teams"], ["Student", "Voice & leadership"]], cta: "Meet our staff" },
  staff: { label: "Our team", title: "Our Staff", emphasis: "learning and care in action.", eyebrow: "Our Staff", intro: "Our teaching staff deliver classroom instruction while also supporting student guidance, supervision and co-curricular activities.", image: "team", details: ["Our administrative and support teams help manage records, finance, boarding, catering, sanitation, security, maintenance and student welfare.", "Together, they create an environment where learners can develop academically and personally."], facts: [["Teaching", "Classroom excellence"], ["Support", "Welfare & operations"], ["Care", "Student guidance"]], cta: "Contact the school" },
  "board-of-governors": { label: "Our team", title: "Governance for Quality and Accountability", emphasis: "for the school community.", eyebrow: "Board of Governors", intro: "The Board of Governors provides institutional governance and oversight, helping ensure that AMHS operates responsibly and remains focused on its educational mission.", image: "board", details: ["The Board supports strategic direction, accountability, school development, learner welfare, policy oversight and engagement with the wider school community.", "The Board works closely with school leadership to keep students at the centre of every decision."], facts: [["Governance", "Strategic oversight"], ["Welfare", "Learner wellbeing"], ["Accountability", "Responsible leadership"]], cta: "Our governance" },
  "pta-leadership": { label: "Our team", title: "Parents as Partners in Education", emphasis: "in every learner's journey.", eyebrow: "PTA Leadership", intro: "AMHS recognises that educating a child requires cooperation between the school and the home.", image: "parents", details: ["The Parents Teachers Association provides an important link between parents, teachers and school administration.", "It supports dialogue on student welfare, discipline, academic performance and school development while strengthening parental participation in education."], facts: [["Partnership", "Home & school"], ["Welfare", "Student support"], ["Participation", "School development"]], cta: "Join the PTA" },
  "student-leadership": { label: "Our team", title: "Learning to Lead by Leading", emphasis: "with responsibility.", eyebrow: "Student Leadership", intro: "Leadership development should begin while young people are still learning.", image: "students", details: ["Student leadership at AMHS provides learners with opportunities to develop responsibility, communication, teamwork, accountability and service.", "Student leaders help promote positive behaviour, represent student concerns and support activities within the school community."], facts: [["Responsibility", "Student voice"], ["Leadership", "Service & teamwork"], ["Growth", "Confidence & accountability"]], cta: "Student life" },
  "success-stories": { label: "Who we are", title: "Every Journey Matters", emphasis: "and every story counts.", eyebrow: "Success Stories", intro: "Success at AMHS is not measured only by examination results. It can be seen when a learner improves academically, develops confidence, discovers a talent, learns a practical skill or becomes an example to others.", image: "success", details: ["More info to be provided.", "The school is committed to recognising the many forms of growth, achievement and contribution made by students."], facts: [["Growth", "Academic & personal"], ["Talent", "Development"], ["Purpose", "Leadership & service"]], cta: "Share your story" },
  "school-policies": { label: "Who we are", title: "Creating a Safe and Responsible Learning Environment", emphasis: "for every learner.", eyebrow: "School Policies", intro: "Our policies establish clear standards for learning, conduct, accountability and student protection.", image: "policies", details: ["At AMHS, every learner has a right to a learning environment free from abuse, neglect, exploitation, violence and discrimination.", "AMHS’s safeguarding framework incorporates the Child Protection Policy, Staff Code of Conduct and Students' Code of Conduct, alongside reporting, prevention, safe recruitment, supervision, guidance and counselling arrangements."], facts: [["Safeguarding", "Child protection"], ["Support", "Guidance & counselling"], ["Standards", "Conduct & accountability"]], cta: "Request a policy" },
  partners: { label: "Who we are", title: "Working Together for Education", emphasis: "with real purpose.", eyebrow: "Our Partners", intro: "Meaningful educational transformation requires collaboration.", image: "partners", details: ["AMHS welcomes responsible partnerships with parents, communities, education authorities, development organisations, businesses, institutions, professionals and well-wishers who share our commitment to improving opportunities for young people.", "Partnership opportunities include student sponsorship, learning materials, ICT, vocational equipment, infrastructure, sports, school exchanges, teacher development, career guidance and technical support."], facts: [["Partnership", "Shared mission"], ["Support", "Student opportunities"], ["Growth", "Infrastructure & skills"]], cta: "Partner with us" },
  facilities: { label: "Who we are", title: "A Campus Built for Learning and Growth", emphasis: "with purpose.", eyebrow: "School Facilities", intro: "Our campus is being developed progressively to provide safe, functional spaces for academic learning, boarding, practical education and co-curricular development.", image: "facilities", details: ["Facilities include classrooms, administration facilities, boarding accommodation, vocational training space, library, computer facilities, kitchen, water and electricity systems, sanitation facilities and playgrounds.", "The school’s longer-term development programme includes science laboratories, additional classrooms, dormitories, sports facilities and other learning infrastructure."], facts: [["Classrooms", "Teaching spaces"], ["Boarding", "Accommodation"], ["Practical", "Skills & learning"]], cta: "Plan a visit" },
  curriculum: { label: "Academics", title: "Learning for Understanding, Application and Life", emphasis: "at AMHS.", eyebrow: "Curriculum", intro: "AMHS follows Uganda's national secondary education curriculum while promoting a learner-centred approach that emphasises understanding, application, creativity and problem-solving.", image: "curriculum", details: ["Academic learning is complemented by continuous assessment, Project-Based Learning, practical skills and co-curricular experiences.", "Our aim is not simply to prepare students for examinations. We want students to become independent thinkers, effective communicators, problem-solvers, innovators and responsible citizens."], facts: [["O-Level", "Core subjects"], ["S1–S6", "Full secondary"], ["A-Level", "Long-term plan"]], cta: "Explore subjects" },
  "academic-calendar": { label: "Academics", title: "A year full of", emphasis: "momentum.", eyebrow: "Academic Calendar", intro: "Term dates, assessment windows and school events to help families plan a focused, fulfilling year.", image: "calendar", details: ["Our calendar balances purposeful study with time to rest, celebrate and take part in the rich life of the school.", "Dates are kept up to date here; families receive important reminders through the school office."], facts: [["Term 1", "Jan — Apr"], ["Term 2", "May — Aug"], ["Term 3", "Sep — Dec"]], cta: "Download calendar" },
  subjects: { label: "Academics", title: "Find the subjects", emphasis: "that spark you.", eyebrow: "Subjects Offered", intro: "Students can pursue a strong core of academic subjects and explore the areas that engage their interests and ambitions.", image: "subjects", details: ["Our experienced teachers support every student to develop solid foundations and make thoughtful choices as they progress through school.", "Learning extends beyond exam preparation; it helps students understand the world and their place within it."], facts: [["STEM", "Sciences & maths"], ["Arts", "Language & humanities"], ["Creative", "Music & design"]], cta: "Talk to academics" },
  library: { label: "Academics", title: "A room full of", emphasis: "new worlds.", eyebrow: "School Library", intro: "The AMHS Library is a calm, welcoming hub for research, reading and the everyday pleasure of discovering something new.", image: "library", details: ["Students have access to carefully selected books, study resources and guidance from staff who know how to turn a question into a useful search.", "It is both a quiet space to concentrate and a lively place to share ideas."], facts: [["4,500+", "Books & resources"], ["6", "Study stations"], ["Daily", "Open access"]], cta: "Visit the library" },
  syllabus: { label: "Academics", title: "A clear route", emphasis: "to achievement.", eyebrow: "National & School Syllabus", intro: "We align national expectations with a carefully sequenced school programme that helps every student make steady, visible progress.", image: "syllabus", details: ["Our subject teams map learning across each year so that knowledge builds securely and students understand what success looks like.", "Families can speak with their child’s teacher for more detailed subject and assessment information."], facts: [["Aligned", "National syllabus"], ["Mapped", "Progression"], ["Shared", "With families"]], cta: "Get syllabus information" },
  admission: { label: "Admission", title: "A warm welcome", emphasis: "awaits.", eyebrow: "Join AMHS", intro: "Choosing a school is a big decision. We are here to make it feel clear, personal and exciting from the first conversation.", image: "admission", details: ["We welcome prospective families to discover the campus, meet our people and learn more about the AMHS experience.", "Our admissions team will help you understand the process, dates and documents you need."], facts: [["2027", "Applications open"], ["3", "Simple steps"], ["1:1", "Admissions support"]], cta: "Apply now" },
  fees: { label: "Admission", title: "Simple, clear", emphasis: "planning.", eyebrow: "Fees Structure", intro: "We present our fees clearly so families can plan with confidence. Please contact admissions for a tailored discussion.", image: "fees", details: ["Fees are reviewed annually and cover high-quality teaching, learning resources, student wellbeing and our rich co-curricular programme.", "We can help explain payment schedules and any support pathways that may be available."], facts: [["Termly", "Payment plans"], ["Clear", "Fee guidance"], ["Helpful", "Admissions team"]], cta: "Ask about fees" },
  uniform: { label: "Admission", title: "Proud to belong.", emphasis: "Ready to learn.", eyebrow: "School Uniform", intro: "Our uniform is practical, comfortable and a shared sign of the AMHS community our students are proud to represent.", image: "uniform", details: ["Families receive a complete uniform list upon admission, including everyday, sports and formal-event items.", "Our school office is happy to help new families with fitting guidance and supplier details."], facts: [["Everyday", "School uniform"], ["Active", "Sports kit"], ["Available", "Local suppliers"]], cta: "Request a uniform list" },
  "our-approach": { label: "Our approach", title: "Purposeful learning.", emphasis: "Real-world courage.", eyebrow: "How we learn", intro: "We help students learn by doing, reflecting, connecting and contributing—because the richest learning changes both the mind and the person.", image: "approach", details: ["Project-based learning gives students a reason to ask good questions, solve real problems and share their work with a genuine audience.", "From school exchanges and brass band to sport, talent development and clubs, every experience grows confidence and connection."], facts: [["PBL", "Hands-on learning"], ["BBC", "Brass Band Club"], ["24", "Clubs & activities"]], cta: "Explore student life" },
  "project-based-learning": { label: "Our approach", title: "Learning by doing.", emphasis: "Thinking with purpose.", eyebrow: "Project-Based Learning", intro: "Project-based learning turns meaningful questions into practical, collaborative work that students can be proud to share.", image: "approach", details: ["Students investigate real challenges, connect ideas across subjects and create solutions for genuine audiences.", "Along the way, they strengthen research, communication, creativity and the confidence to keep improving their work."], facts: [["PBL", "Learning by doing"], ["Teamwork", "Shared solutions"], ["Real-world", "Meaningful projects"]], cta: "Explore our approach" },
  "brass-band-club": { label: "Our approach", title: "Find your rhythm.", emphasis: "Play as one.", eyebrow: "Brass Band Club", intro: "The AMHS Brass Band Club builds musicianship, discipline and pride through the shared energy of performance.", image: "life", details: ["Students learn to listen closely, practise with purpose and contribute their individual sound to something bigger.", "From rehearsals to school events, the band creates memorable moments and a strong sense of belonging."], facts: [["BBC", "Brass Band Club"], ["Music", "Shared expression"], ["Teamwork", "Playing as one"]], cta: "Discover student life" },
  "games-and-sport": { label: "Our approach", title: "Play with heart.", emphasis: "Grow with grit.", eyebrow: "Games & Sports", intro: "Sport at AMHS develops healthy habits, teamwork and the courage to keep showing up for one another.", image: "life", details: ["Students can take part at every level, learning new skills, setting goals and enjoying the value of active play.", "Competition matters, but character matters more: respect, resilience and a generous team spirit guide every game."], facts: [["8", "Sports teams"], ["Active", "Every learner"], ["Teamwork", "On and off the field"]], cta: "Explore student life" },
  "talent-development": { label: "Our approach", title: "Potential becomes", emphasis: "something remarkable.", eyebrow: "Talent Development", intro: "We help students notice their strengths, practise deliberately and find the confidence to let their talents grow.", image: "life", details: ["Whether a student is drawn to music, sport, leadership, creativity or public speaking, there is room to explore and improve.", "Supportive mentors help each learner set ambitious goals and celebrate the progress that comes from steady effort."], facts: [["Creative", "Arts & expression"], ["Active", "Sport & wellbeing"], ["Leadership", "Confident voices"]], cta: "Discover student life" },
  "associations-and-clubs": { label: "Our approach", title: "Find your people.", emphasis: "Make your mark.", eyebrow: "Associations & Clubs", intro: "Our associations and clubs give every student a place to explore interests, form friendships and contribute to school life.", image: "life", details: ["Students can join established clubs or help shape new ones around the ideas and causes that matter to them.", "These communities build confidence, responsibility and the joy of doing something worthwhile together."], facts: [["24", "Clubs & societies"], ["Every interest", "A place to belong"], ["Student-led", "Ideas welcome"]], cta: "Explore student life" },
  "students-life": { label: "Student life", title: "There is more", emphasis: "to discover here.", eyebrow: "Life at AMHS", intro: "The school day is only the beginning. Student life at AMHS is where friendships form, talents emerge and memories are made.", image: "life", details: ["There is a place for every kind of interest: sport, music, creative arts, debating, service, science and much more.", "We want each young person to find something that makes them feel capable, connected and fully themselves."], facts: [["24", "Clubs & societies"], ["8", "Sports teams"], ["100%", "Room to belong"]], cta: "See our approach" },
  "get-involved": { label: "Get involved", title: "A brighter future", emphasis: "takes all of us.", eyebrow: "Support AMHS", intro: "You can help create opportunities that reach far beyond the classroom and last long after school.", image: "involved", details: ["Whether you give, sponsor a child, share expertise or help build an exchange, your involvement can change what is possible for a young person.", "Every contribution is an investment in confident learners and compassionate future leaders."], facts: [["Give", "Create opportunity"], ["Sponsor", "Change a future"], ["Connect", "Share expertise"]], cta: "Make a difference" },
  "news-and-events": { label: "News and Events", title: "A school community in motion", emphasis: "with learning, celebration and service.", eyebrow: "News and Events", intro: "AMHS is building a campus culture that celebrates learning, milestones, school life and community engagement.", image: "curriculum", details: ["News and events at AMHS will highlight student achievement, school activities, outreach, open days, community partnerships and meaningful moments across the academic year.", "We welcome families, partners and friends to follow the life of the school and celebrate the progress of our learners."], facts: [["School life", "Student achievement"], ["Community", "Events & outreach"], ["Growth", "Shared milestones"]], cta: "Stay connected" },
  "contact-us": { label: "Contact Us", title: "We are here to help", emphasis: "and to welcome you.", eyebrow: "Contact AMHS", intro: "We are happy to help with admissions enquiries, general school questions, partnerships and support opportunities.", image: "involved", details: ["Whether you want to find out more about the school, request a visit, discuss sponsorship or ask about admissions, the AMHS team is ready to assist.", "Please use the details below to get in touch and we will help you with the next step."], facts: [["Admissions", "School enquiries"], ["Partnerships", "School exchanges"], ["Support", "Sponsorship & giving"]], cta: "Get in touch" },
  "school-exchange-programmes": { label: "Get involved", title: "A wider world", emphasis: "within reach.", eyebrow: "School Exchange Programmes", intro: "Exchange programmes help students see new perspectives, build friendships across borders and bring fresh ideas back to AMHS.", image: "exchange", details: ["We welcome partnerships with schools and organisations that share our belief in open-minded, globally engaged education.", "Get in touch to explore an exchange that is purposeful, safe and enriching for young people."], facts: [["6", "Partner links"], ["3", "Countries"], ["∞", "New perspectives"]], cta: "Start a conversation" },
};

type PageFamily = "story" | "people" | "learning" | "practical" | "experience" | "community";

const pageHeadings: Record<string, [string, string]> = {
  academics: ["Ambition with", "the right support."], about: ["The values behind", "our school."], "amhs-roots": ["A story worth", "carrying forward."],
  team: ["Teaching, mentoring,", "and belonging."], staff: ["Dedicated to each", "student’s growth."], "board-of-governors": ["Leadership with students", "at the centre."],
  "pta-leadership": ["Home and school", "working together."], "student-leadership": ["A voice, a responsibility,", "a chance to lead."], "success-stories": ["What our community", "carries forward."],
  "school-policies": ["The guidance that keeps", "our community safe."], partners: ["Partnerships with", "real purpose."], facilities: ["A campus ready for", "every kind of learning."],
  curriculum: ["A clear journey through", "knowledge and possibility."], "academic-calendar": ["Plan the year", "with confidence."], subjects: ["Areas of study that", "open up choices."],
  library: ["Time and space", "to think deeply."], syllabus: ["What students learn,", "and how it builds."], admission: ["Everything families need", "to begin well."],
  fees: ["Straightforward support", "for family planning."], uniform: ["What students need", "to feel ready."], "our-approach": ["How learning becomes", "part of who students are."],
  "project-based-learning": ["Questions, action,", "and meaningful work."], "brass-band-club": ["Practice, performance,", "and pride."], "games-and-sport": ["A place to play,", "compete, and grow."],
  "talent-development": ["A pathway for", "every strength."], "associations-and-clubs": ["Interests become", "a sense of belonging."], "students-life": ["A school day with", "more to discover."],
  "get-involved": ["Ways to make", "a lasting difference."], "news-and-events": ["What is happening", "across the school."], "contact-us": ["A warm welcome", "from the AMHS team."], "school-exchange-programmes": ["New perspectives", "that travel both ways."],
};

const actionDestinations: Record<string, string> = {
  academics: "/subjects", about: "/team", "amhs-roots": "/about", team: "/staff", staff: "mailto:info@amhs.ac.ug",
  "board-of-governors": "mailto:info@amhs.ac.ug", "pta-leadership": "mailto:info@amhs.ac.ug", "student-leadership": "/students-life",
  "success-stories": "mailto:info@amhs.ac.ug", "school-policies": "mailto:info@amhs.ac.ug", partners: "mailto:info@amhs.ac.ug", facilities: "/apply-now",
  curriculum: "/subjects", "academic-calendar": "mailto:info@amhs.ac.ug", subjects: "mailto:info@amhs.ac.ug", library: "mailto:info@amhs.ac.ug",
  syllabus: "mailto:info@amhs.ac.ug", admission: "/apply-now", fees: "mailto:admissions@amhs.ac.ug", uniform: "mailto:admissions@amhs.ac.ug",
  "our-approach": "/students-life", "project-based-learning": "/our-approach", "brass-band-club": "/students-life", "games-and-sport": "/students-life",
  "talent-development": "/students-life", "associations-and-clubs": "/students-life", "students-life": "/our-approach", "get-involved": "/donate",
  "news-and-events": "/news-and-events", "contact-us": "mailto:info@amhs.sc.ug",
  "school-exchange-programmes": "mailto:info@amhs.ac.ug",
};

const familyContent: Record<PageFamily, { label: string; title: string; emphasis: string; description: string }> = {
  story: { label: "The bigger picture", title: "A shared", emphasis: "sense of purpose.", description: "The details below show the people, values and experiences that shape this part of AMHS." },
  people: { label: "People first", title: "The relationships", emphasis: "behind the work.", description: "Every role contributes to a school where young people are known, challenged and supported." },
  learning: { label: "Learning in practice", title: "Strong foundations.", emphasis: "Wider horizons.", description: "This is how students build knowledge, confidence and the habits that carry learning forward." },
  practical: { label: "Useful information", title: "The details", emphasis: "families need.", description: "Clear information helps students and families plan confidently for the next step." },
  experience: { label: "Beyond the classroom", title: "A chance to", emphasis: "take part and grow.", description: "These experiences give students room to practise, contribute and find what matters to them." },
  community: { label: "Together with AMHS", title: "Shared effort.", emphasis: "Real opportunity.", description: "This work connects the school with families, partners and a wider community of support." },
};

const mediaClass = (key: string) => `page-photo image-${key}`;

function getPageFamily(slug: string): PageFamily {
  if (["academics", "curriculum", "library"].includes(slug)) return "learning";
  if (["academic-calendar", "subjects", "syllabus", "fees", "uniform", "school-policies", "facilities", "admission"].includes(slug)) return "practical";
  if (["team", "staff", "board-of-governors", "pta-leadership", "student-leadership"].includes(slug)) return "people";
  if (["our-approach", "project-based-learning", "brass-band-club", "games-and-sport", "talent-development", "associations-and-clubs", "students-life"].includes(slug)) return "experience";
  if (["partners", "get-involved", "news-and-events", "contact-us", "school-exchange-programmes"].includes(slug)) return "community";
  return "story";
}

function PageAction({ slug, label }: { slug: string; label: string }) {
  const href = actionDestinations[slug] ?? "/apply-now";
  const content = <>{label} <Arrow /></>;
  return href.startsWith("mailto:")
    ? <a className="button button-navy" href={href}>{content}</a>
    : <Link className="button button-navy" href={href}>{content}</Link>;
}

function TopicOverview({ page, family }: { page: PageInfo; family: PageFamily }) {
  const content = familyContent[family];
  return <section className={`topic-section topic-section--${family}`}>
    <div className="container">
      <div className="topic-heading">
        <div><p className="eyebrow"><span /> {content.label}</p><h2>{content.title}<br /><em>{content.emphasis}</em></h2></div>
        <p>{content.description}</p>
      </div>
      <div className="topic-grid">
        {page.facts.map(([value, label], index) => <article className="topic-card" key={`${value}-${label}`}>
          <span className="topic-number">0{index + 1}</span><strong>{value}</strong><h3>{label}</h3>
          <p>{page.details[index] ?? `Find out more about ${label.toLowerCase()} and what it means for the AMHS community.`}</p>
        </article>)}
      </div>
    </div>
  </section>;
}

function ProfileDirectory({ type }: { type: "team" | "staff" }) {
  const isLeadership = type === "team";
  const profiles = peopleProfiles[type];
  return <section className="profiles-section">
    <div className="container">
      <div className="profiles-heading">
        <div><p className="eyebrow"><span /> {isLeadership ? "Meet the leadership team" : "Meet our staff"}</p><h2>{isLeadership ? "Guided by care." : "Expertise in every"}<br /><em>{isLeadership ? "Focused on every learner." : "part of school life."}</em></h2></div>
        <p>{isLeadership ? "Our leadership team creates the conditions for excellent learning, strong relationships and a school community that stays true to its values." : "Our teaching and support teams bring specialist knowledge, personal care and a shared commitment to helping young people flourish."}</p>
      </div>
      <div className="profile-grid">
        {profiles.map((profile) => <article className="profile-card" key={profile.name}>
          <div className={`profile-avatar${profile.image ? " has-photo" : ""}`} aria-hidden="true" style={profile.image ? { backgroundImage: `url(${profile.image})` } : undefined}>{profile.image ? "" : profile.initials}</div>
          <p>{profile.role}</p><h3>{profile.name}</h3><span className="profile-rule" />
          <p className="profile-bio">{profile.bio}</p>
        </article>)}
      </div>
      <p className="profiles-contact">For a school enquiry or to reach the right member of the team, <a href="mailto:info@amhs.ac.ug">contact the school office</a>.</p>
    </div>
  </section>;
}

export function generateStaticParams() {
  return [...Object.keys(pages), "apply-now", "donate", "sponsor-a-child"].map((slug) => ({ slug }));
}

export default async function ContentPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  if (slug === "apply-now") return <ApplyPage />;
  if (slug === "donate" || slug === "sponsor-a-child") return <GivingPage sponsor={slug === "sponsor-a-child"} />;
  const page = pages[slug];
  if (!page) notFound();
  const [sectionTitle, sectionEmphasis] = pageHeadings[slug] ?? [page.eyebrow, "at AMHS."];
  const family = getPageFamily(slug);

  return <>
    <section className="page-hero"><div className={mediaClass(page.image)} /><div className="page-hero-overlay" /><div className="container page-hero-content"><p className="eyebrow eyebrow-light"><span /> {page.label}</p><h1>{page.title}<br /><em>{page.emphasis}</em></h1><p>{page.intro}</p></div></section>
    <section className={`content-section content-section--${family} container`}><div className="content-copy"><p className="eyebrow"><span /> {page.eyebrow}</p><h2>{sectionTitle}<br /><em>{sectionEmphasis}</em></h2>{page.details.map((detail) => <p key={detail}>{detail}</p>)}<PageAction slug={slug} label={page.cta ?? "Get in touch"} /></div><aside className="facts-card"><p>At a glance</p>{page.facts.map(([value, label]) => <div key={`${value}-${label}`}><strong>{value}</strong><span>{label}</span></div>)}</aside></section>
    {slug === "team" || slug === "staff" ? <ProfileDirectory type={slug} /> : <TopicOverview page={page} family={family} />}
  </>;
}

function ApplyPage() { return <><section className="page-hero page-hero-short"><div className="page-photo image-admission" /><div className="page-hero-overlay" /><div className="container page-hero-content"><p className="eyebrow eyebrow-light"><span /> Admission</p><h1>Let&apos;s begin<br /><em>together.</em></h1><p>Your child&apos;s AMHS story can start with a simple conversation.</p></div></section><section className="application-section container"><div className="application-aside"><p className="eyebrow"><span /> A personal process</p><h2>Every application starts with <em>getting to know you.</em></h2><p>We take time to understand each applicant and help your family decide whether AMHS is the right fit.</p><ol><li><span>01</span> Send your enquiry</li><li><span>02</span> Speak with admissions</li><li><span>03</span> Visit, apply, and belong</li></ol><a href="mailto:admissions@amhs.ac.ug" className="text-link">Have a question? Email us <Arrow /></a></div><AdmissionForm /></section></> }

function GivingPage({ sponsor }: { sponsor: boolean }) { const heading = sponsor ? ["A chance to learn.", "A future to build."] : ["Give a little.", "Change a lot."]; return <><section className="page-hero page-hero-short"><div className="page-photo image-involved" /><div className="page-hero-overlay" /><div className="container page-hero-content"><p className="eyebrow eyebrow-light"><span /> {sponsor ? "Sponsor a child" : "Donate"}</p><h1>{heading[0]}<br /><em>{heading[1]}</em></h1><p>{sponsor ? "Your monthly support can keep a child learning, growing and dreaming." : "Your gift goes directly toward opening up opportunity for our students."}</p></div></section><section className="giving-section container"><div className="giving-copy"><p className="eyebrow"><span /> Make an impact</p><h2>Small acts create <em>lasting possibility.</em></h2><p>When our wider community steps in, students can access the resources, experiences and encouragement they need to go further.</p><div className="impact-list"><span><b>01</b> Learning resources</span><span><b>02</b> Participation in activities</span><span><b>03</b> Student wellbeing</span></div></div><GivingOptions sponsor={sponsor} /></section></> }
