import Link from "next/link";
import { notFound } from "next/navigation";
import { AdmissionForm } from "../../components/admission-form";
import { Arrow } from "../../components/icons";
import { GivingOptions } from "../../components/giving-options";

type PageInfo = { label: string; title: string; emphasis: string; intro: string; image: string; eyebrow: string; details: string[]; facts: [string, string][]; cta?: string };

const pages: Record<string, PageInfo> = {
  academics: { label: "Academics", title: "A strong foundation", emphasis: "for every future.", eyebrow: "Learning at AMHS", intro: "Academic life at AMHS balances ambition with attentive support, helping every student take the next step with confidence.", image: "curriculum", details: ["Our teachers make learning purposeful, challenging and accessible, giving students the knowledge and habits to flourish in every subject.", "Alongside the national curriculum, students encounter opportunities to explore, create and connect their learning to a bigger world."], facts: [["S1–S6", "Full secondary"], ["12", "Core subjects"], ["24", "Learning pathways"]], cta: "Explore subjects" },
  about: { label: "Who we are", title: "A school built", emphasis: "for possibility.", eyebrow: "About AMHS", intro: "For four decades, Asaba Memorial High School has been a place where young people are known, encouraged, and equipped to contribute with confidence.", image: "about", details: ["We are a diverse community of students, families, teachers and alumni united by the belief that education can change a life.", "Our values guide the way we learn together: excellence without arrogance, courage with kindness, and service with purpose."], facts: [["1985", "Founded"], ["750+", "Students"], ["60+", "Dedicated staff"]], cta: "Meet our community" },
  "amhs-roots": { label: "Who we are", title: "Our roots run", emphasis: "deep.", eyebrow: "AMHS Roots", intro: "Our story began with a simple conviction: every child in our community deserves a meaningful, excellent education.", image: "roots", details: ["From a small group of determined families and educators, AMHS has grown into a school with a lasting impact across Uganda and beyond.", "The spirit of those early years—resourceful, caring and forward-looking—still shapes us today."], facts: [["40", "Years of service"], ["4", "Generations of alumni"], ["1", "Enduring purpose"]], cta: "Read our story" },
  team: { label: "Who we are", title: "People who bring", emphasis: "learning to life.", eyebrow: "Our Team", intro: "Great schools are made by great people. Meet the leaders, educators and mentors who make AMHS feel like home.", image: "team", details: ["Our staff bring expertise, energy and wholehearted care to each day. They teach their subjects brilliantly—and they also coach, listen, encourage and inspire.", "Together, they create a culture in which every student can be seen and supported."], facts: [["60+", "Staff members"], ["8:1", "Student support ratio"], ["24", "Co-curricular mentors"]], cta: "Meet our staff" },
  staff: { label: "Our team", title: "Meet the people", emphasis: "behind the care.", eyebrow: "Our Staff", intro: "The commitment and expertise of our teaching and support staff is at the heart of the AMHS experience.", image: "team", details: ["Each member of our staff shares a deep belief in the potential of young people.", "They build strong relationships, spark curiosity and create the calm, focused conditions in which students thrive."], facts: [["48", "Teachers"], ["12", "Support staff"], ["100%", "Committed"]], cta: "Contact the school" },
  "board-of-governors": { label: "Our team", title: "Stewardship for a", emphasis: "stronger future.", eyebrow: "Board of Governors", intro: "Our Board provides thoughtful governance, strategic direction and enduring care for the mission of AMHS.", image: "board", details: ["They bring a broad range of professional experience, a shared commitment to education and a deep connection to the community we serve.", "The Board works closely with school leadership to make decisions that keep students at the centre."], facts: [["9", "Board members"], ["4", "Standing committees"], ["1", "Shared mission"]], cta: "Our governance" },
  "pta-leadership": { label: "Our team", title: "Families at the", emphasis: "heart of school.", eyebrow: "PTA Leadership", intro: "The Parent–Teacher Association strengthens the bridge between home and school, helping every learner feel supported.", image: "parents", details: ["Our PTA gives families a meaningful voice and creates practical ways to support learning, wellbeing and community events.", "Together, we make AMHS more welcoming, connected and resilient."], facts: [["12", "PTA leaders"], ["3", "Community events"], ["1", "Shared commitment"]], cta: "Join the PTA" },
  "student-leadership": { label: "Our team", title: "Leadership begins", emphasis: "with listening.", eyebrow: "Student Leadership", intro: "At AMHS, students do not wait until adulthood to make a contribution. They lead, organise and speak up today.", image: "students", details: ["Our student leaders represent their peers, welcome new voices and model service across school life.", "The experience develops self-belief, responsibility and an enduring habit of positive action."], facts: [["30", "Student leaders"], ["6", "Leadership teams"], ["100%", "Student voice"]], cta: "Student life" },
  "success-stories": { label: "Who we are", title: "The impact is", emphasis: "written in lives.", eyebrow: "Success Stories", intro: "The truest measure of our work is what our students carry forward: confidence, curiosity, character and a desire to make things better.", image: "success", details: ["Our alumni lead in universities, businesses, communities and creative fields. More importantly, they remain people of purpose and generosity.", "These stories remind us why an excellent education matters."], facts: [["2,000+", "Alumni network"], ["18", "Countries represented"], ["1", "Proud community"]], cta: "Share your story" },
  "school-policies": { label: "Who we are", title: "Clear principles.", emphasis: "Caring practice.", eyebrow: "School Policies", intro: "Our policies help make AMHS a safe, respectful and focused environment in which every learner can flourish.", image: "policies", details: ["Policies are reviewed regularly to make sure they reflect our values, meet national requirements and support the wellbeing of our whole community.", "For a printed copy or a question about any policy, please contact the school office."], facts: [["Safeguarding", "Student wellbeing"], ["Respect", "Community conduct"], ["Integrity", "Academic honesty"]], cta: "Request a policy" },
  partners: { label: "Who we are", title: "Better together,", emphasis: "always.", eyebrow: "Our Partners", intro: "Our partners expand what is possible for AMHS students, from resources and expertise to meaningful opportunities beyond our gates.", image: "partners", details: ["We are grateful to the organisations, alumni and friends who invest time, insight and resources in our community.", "Partnerships help students encounter new ideas and see a wider world of possibility."], facts: [["15+", "Active partners"], ["6", "Exchange links"], ["40", "Years of trust"]], cta: "Partner with us" },
  facilities: { label: "Who we are", title: "Spaces made for", emphasis: "discovery.", eyebrow: "School Facilities", intro: "Our campus is designed to support focused learning, rich creativity, active play and a genuine sense of belonging.", image: "facilities", details: ["From our classrooms and laboratories to the library, playing fields and creative spaces, each part of campus supports a different kind of learning.", "We continue to invest in welcoming, purposeful environments for our growing community."], facts: [["12", "Learning spaces"], ["1", "Well-stocked library"], ["5", "Sporting areas"]], cta: "Plan a visit" },
  curriculum: { label: "Academics", title: "Learning that opens", emphasis: "every door.", eyebrow: "Curriculum", intro: "Our broad, challenging curriculum builds deep subject knowledge alongside the creativity and critical thinking needed for tomorrow.", image: "curriculum", details: ["We follow the national curriculum while enriching it with inquiry, collaboration and opportunities to apply learning in authentic contexts.", "Every subject is a chance for students to become more articulate, capable and curious."], facts: [["S1–S6", "Full secondary"], ["12", "Core subjects"], ["24", "Choice pathways"]], cta: "Explore subjects" },
  "academic-calendar": { label: "Academics", title: "A year full of", emphasis: "momentum.", eyebrow: "Academic Calendar", intro: "Term dates, assessment windows and school events to help families plan a focused, fulfilling year.", image: "calendar", details: ["Our calendar balances purposeful study with time to rest, celebrate and take part in the rich life of the school.", "Dates are kept up to date here; families receive important reminders through the school office."], facts: [["Term 1", "Jan — Apr"], ["Term 2", "May — Aug"], ["Term 3", "Sep — Dec"]], cta: "Download calendar" },
  subjects: { label: "Academics", title: "Find the subjects", emphasis: "that spark you.", eyebrow: "Subjects Offered", intro: "Students can pursue a strong core of academic subjects and explore the areas that engage their interests and ambitions.", image: "subjects", details: ["Our experienced teachers support every student to develop solid foundations and make thoughtful choices as they progress through school.", "Learning extends beyond exam preparation; it helps students understand the world and their place within it."], facts: [["STEM", "Sciences & maths"], ["Arts", "Language & humanities"], ["Creative", "Music & design"]], cta: "Talk to academics" },
  library: { label: "Academics", title: "A room full of", emphasis: "new worlds.", eyebrow: "School Library", intro: "The AMHS Library is a calm, welcoming hub for research, reading and the everyday pleasure of discovering something new.", image: "library", details: ["Students have access to carefully selected books, study resources and guidance from staff who know how to turn a question into a useful search.", "It is both a quiet space to concentrate and a lively place to share ideas."], facts: [["4,500+", "Books & resources"], ["6", "Study stations"], ["Daily", "Open access"]], cta: "Visit the library" },
  syllabus: { label: "Academics", title: "A clear route", emphasis: "to achievement.", eyebrow: "National & School Syllabus", intro: "We align national expectations with a carefully sequenced school programme that helps every student make steady, visible progress.", image: "syllabus", details: ["Our subject teams map learning across each year so that knowledge builds securely and students understand what success looks like.", "Families can speak with their child’s teacher for more detailed subject and assessment information."], facts: [["Aligned", "National syllabus"], ["Mapped", "Progression"], ["Shared", "With families"]], cta: "Get syllabus information" },
  admission: { label: "Admission", title: "A warm welcome", emphasis: "awaits.", eyebrow: "Join AMHS", intro: "Choosing a school is a big decision. We are here to make it feel clear, personal and exciting from the first conversation.", image: "admission", details: ["We welcome prospective families to discover the campus, meet our people and learn more about the AMHS experience.", "Our admissions team will help you understand the process, dates and documents you need."], facts: [["2027", "Applications open"], ["3", "Simple steps"], ["1:1", "Admissions support"]], cta: "Apply now" },
  fees: { label: "Admission", title: "Simple, clear", emphasis: "planning.", eyebrow: "Fees Structure", intro: "We present our fees clearly so families can plan with confidence. Please contact admissions for a tailored discussion.", image: "fees", details: ["Fees are reviewed annually and cover high-quality teaching, learning resources, student wellbeing and our rich co-curricular programme.", "We can help explain payment schedules and any support pathways that may be available."], facts: [["Termly", "Payment plans"], ["Clear", "Fee guidance"], ["Helpful", "Admissions team"]], cta: "Ask about fees" },
  uniform: { label: "Admission", title: "Proud to belong.", emphasis: "Ready to learn.", eyebrow: "School Uniform", intro: "Our uniform is practical, comfortable and a shared sign of the AMHS community our students are proud to represent.", image: "uniform", details: ["Families receive a complete uniform list upon admission, including everyday, sports and formal-event items.", "Our school office is happy to help new families with fitting guidance and supplier details."], facts: [["Everyday", "School uniform"], ["Active", "Sports kit"], ["Available", "Local suppliers"]], cta: "Request a uniform list" },
  "our-approach": { label: "Our approach", title: "Purposeful learning.", emphasis: "Real-world courage.", eyebrow: "How we learn", intro: "We help students learn by doing, reflecting, connecting and contributing—because the richest learning changes both the mind and the person.", image: "approach", details: ["Project-based learning gives students a reason to ask good questions, solve real problems and share their work with a genuine audience.", "From school exchanges and brass band to sport, talent development and clubs, every experience grows confidence and connection."], facts: [["PBL", "Hands-on learning"], ["BBC", "Brass Band Club"], ["24", "Clubs & activities"]], cta: "Explore student life" },
  "project-based-learning": { label: "Our approach", title: "Learning by doing.", emphasis: "Thinking with purpose.", eyebrow: "Project-Based Learning", intro: "Project-based learning turns meaningful questions into practical, collaborative work that students can be proud to share.", image: "approach", details: ["Students investigate real challenges, connect ideas across subjects and create solutions for genuine audiences.", "Along the way, they strengthen research, communication, creativity and the confidence to keep improving their work."], facts: [["PBL", "Learning by doing"], ["Teamwork", "Shared solutions"], ["Real-world", "Meaningful projects"]], cta: "Explore our approach" },
  "brass-band-club": { label: "Our approach", title: "Find your rhythm.", emphasis: "Play as one.", eyebrow: "Brass Band Club", intro: "The AMHS Brass Band Club builds musicianship, discipline and pride through the shared energy of performance.", image: "life", details: ["Students learn to listen closely, practise with purpose and contribute their individual sound to something bigger.", "From rehearsals to school events, the band creates memorable moments and a strong sense of belonging."], facts: [["BBC", "Brass Band Club"], ["Music", "Shared expression"], ["Teamwork", "Playing as one"]], cta: "Discover student life" },
  "games-and-sport": { label: "Our approach", title: "Play with heart.", emphasis: "Grow with grit.", eyebrow: "Games & Sports", intro: "Sport at AMHS develops healthy habits, teamwork and the courage to keep showing up for one another.", image: "life", details: ["Students can take part at every level, learning new skills, setting goals and enjoying the value of active play.", "Competition matters, but character matters more: respect, resilience and a generous team spirit guide every game."], facts: [["8", "Sports teams"], ["Active", "Every learner"], ["Teamwork", "On and off the field"]], cta: "Explore student life" },
  "talent-development": { label: "Our approach", title: "Potential becomes", emphasis: "something remarkable.", eyebrow: "Talent Development", intro: "We help students notice their strengths, practise deliberately and find the confidence to let their talents grow.", image: "life", details: ["Whether a student is drawn to music, sport, leadership, creativity or public speaking, there is room to explore and improve.", "Supportive mentors help each learner set ambitious goals and celebrate the progress that comes from steady effort."], facts: [["Creative", "Arts & expression"], ["Active", "Sport & wellbeing"], ["Leadership", "Confident voices"]], cta: "Discover student life" },
  "associations-and-clubs": { label: "Our approach", title: "Find your people.", emphasis: "Make your mark.", eyebrow: "Associations & Clubs", intro: "Our associations and clubs give every student a place to explore interests, form friendships and contribute to school life.", image: "life", details: ["Students can join established clubs or help shape new ones around the ideas and causes that matter to them.", "These communities build confidence, responsibility and the joy of doing something worthwhile together."], facts: [["24", "Clubs & societies"], ["Every interest", "A place to belong"], ["Student-led", "Ideas welcome"]], cta: "Explore student life" },
  "students-life": { label: "Student life", title: "There is more", emphasis: "to discover here.", eyebrow: "Life at AMHS", intro: "The school day is only the beginning. Student life at AMHS is where friendships form, talents emerge and memories are made.", image: "life", details: ["There is a place for every kind of interest: sport, music, creative arts, debating, service, science and much more.", "We want each young person to find something that makes them feel capable, connected and fully themselves."], facts: [["24", "Clubs & societies"], ["8", "Sports teams"], ["100%", "Room to belong"]], cta: "See our approach" },
  "get-involved": { label: "Get involved", title: "A brighter future", emphasis: "takes all of us.", eyebrow: "Support AMHS", intro: "You can help create opportunities that reach far beyond the classroom and last long after school.", image: "involved", details: ["Whether you give, sponsor a child, share expertise or help build an exchange, your involvement can change what is possible for a young person.", "Every contribution is an investment in confident learners and compassionate future leaders."], facts: [["Give", "Create opportunity"], ["Sponsor", "Change a future"], ["Connect", "Share expertise"]], cta: "Make a difference" },
  "school-exchange-programmes": { label: "Get involved", title: "A wider world", emphasis: "within reach.", eyebrow: "School Exchange Programmes", intro: "Exchange programmes help students see new perspectives, build friendships across borders and bring fresh ideas back to AMHS.", image: "exchange", details: ["We welcome partnerships with schools and organisations that share our belief in open-minded, globally engaged education.", "Get in touch to explore an exchange that is purposeful, safe and enriching for young people."], facts: [["6", "Partner links"], ["3", "Countries"], ["∞", "New perspectives"]], cta: "Start a conversation" },
};

const mediaClass = (key: string) => `page-photo image-${key}`;

export function generateStaticParams() {
  return [...Object.keys(pages), "apply-now", "donate", "sponsor-a-child"].map((slug) => ({ slug }));
}

export default async function ContentPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  if (slug === "apply-now") return <ApplyPage />;
  if (slug === "donate" || slug === "sponsor-a-child") return <GivingPage sponsor={slug === "sponsor-a-child"} />;
  const page = pages[slug];
  if (!page) notFound();
  return <>
    <section className="page-hero"><div className={mediaClass(page.image)} /><div className="page-hero-overlay" /><div className="container page-hero-content"><p className="eyebrow eyebrow-light"><span /> {page.label}</p><h1>{page.title}<br /><em>{page.emphasis}</em></h1><p>{page.intro}</p></div></section>
    <section className="content-section container"><div className="content-copy"><p className="eyebrow"><span /> {page.eyebrow}</p><h2>Thoughtfully designed<br /><em>for every learner.</em></h2>{page.details.map((detail) => <p key={detail}>{detail}</p>)}<Link href="/apply-now" className="button button-navy">{page.cta ?? "Get in touch"} <Arrow /></Link></div><aside className="facts-card"><p>At a glance</p>{page.facts.map(([value, label]) => <div key={value}><strong>{value}</strong><span>{label}</span></div>)}</aside></section>
    <section className="wide-photo-section"><div className={`wide-photo ${mediaClass(page.image)}`} /><div className="container"><div className="wide-photo-card"><p className="eyebrow"><span /> The AMHS way</p><h2>Growing capable,<br /><em>compassionate people.</em></h2><p>We see potential in every student, and bring our best to helping it grow.</p></div></div></section>
    <section className="route-panel"><div className="container"><p className="eyebrow eyebrow-light"><span /> Your next step</p><h2>Come and see what<br /><em>is possible.</em></h2><Link className="button button-gold" href="/apply-now">Start an enquiry <Arrow /></Link></div></section>
  </>;
}

function ApplyPage() { return <><section className="page-hero page-hero-short"><div className="page-photo image-admission" /><div className="page-hero-overlay" /><div className="container page-hero-content"><p className="eyebrow eyebrow-light"><span /> Admission</p><h1>Let&apos;s begin<br /><em>together.</em></h1><p>Your child&apos;s AMHS story can start with a simple conversation.</p></div></section><section className="application-section container"><div className="application-aside"><p className="eyebrow"><span /> A personal process</p><h2>Every application starts with <em>getting to know you.</em></h2><p>We take time to understand each applicant and help your family decide whether AMHS is the right fit.</p><ol><li><span>01</span> Send your enquiry</li><li><span>02</span> Speak with admissions</li><li><span>03</span> Visit, apply, and belong</li></ol><a href="mailto:admissions@amhs.ac.ug" className="text-link">Have a question? Email us <Arrow /></a></div><AdmissionForm /></section></> }

function GivingPage({ sponsor }: { sponsor: boolean }) { const heading = sponsor ? ["A chance to learn.", "A future to build."] : ["Give a little.", "Change a lot."]; return <><section className="page-hero page-hero-short"><div className="page-photo image-involved" /><div className="page-hero-overlay" /><div className="container page-hero-content"><p className="eyebrow eyebrow-light"><span /> {sponsor ? "Sponsor a child" : "Donate"}</p><h1>{heading[0]}<br /><em>{heading[1]}</em></h1><p>{sponsor ? "Your monthly support can keep a child learning, growing and dreaming." : "Your gift goes directly toward opening up opportunity for our students."}</p></div></section><section className="giving-section container"><div className="giving-copy"><p className="eyebrow"><span /> Make an impact</p><h2>Small acts create <em>lasting possibility.</em></h2><p>When our wider community steps in, students can access the resources, experiences and encouragement they need to go further.</p><div className="impact-list"><span><b>01</b> Learning resources</span><span><b>02</b> Participation in activities</span><span><b>03</b> Student wellbeing</span></div></div><GivingOptions sponsor={sponsor} /></section></> }
